[package]
name = "client_lib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]
path = "src/client.rs"

[build]
target = "x86_64-unknown-linux-gnu"

[build-dependencies]
csbindgen = "1.2.0"
