[package]
name = "client_lib"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["dylib"]
path = "src/lib.rs"

[build]
target = "x86_64-unknown-linux-gnu"

[dependencies]
libsql = "0.1.11"
lazy_static = "1.4"

[build-dependencies]
csbindgen = "1.2.0"
