name: dotnet test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "7.0.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Cache Rust Bindings
        id: cache-rust-bindings
        uses: actions/cache@v2
        with:
          path: |
            rust-bindings/target/release/libcsharp_bindings.*
            rust-bindings/c-sharp-bindings/bindings/Libsql.g.cs
          key: rust-bindings-${{ hashFiles('./generate-bindings.sh') }}
          restore-keys: |
            rust-bindings-

      - name: Generate bindings
        if: steps.cache-rust-libraries.outputs.cache-hit != 'true' || steps.cache-rust-bindings.outputs.cache-hit != 'true'
        run: ./generate-bindings.sh

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
